name: Lint Python
description: Linting for Python projects
inputs:
  exclude_trailing_comma_path:
    required: false
    description: Ignore trailing comma changes in given path
    default: ''
  working_directory:
    required: false
    description: "Working directory, defaults to GITHUB_WORKSPACE"
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - run: find . -name '*.json' -type f -print0 | xargs -I {} -0 python -m json.tool --indent 2 --no-ensure-ascii {} {}
      shell: bash

    - uses: moneymeets/moneymeets-composite-actions/check-git-diff@master

    - run: echo "ruff-available=$(poetry show ruff -q ; echo $?)" >> $GITHUB_OUTPUT
      id: detect-ruff
      shell: bash

    - name: Run linter
      if: steps.detect-ruff.outputs.ruff-available == 0
      run: poetry run ruff check ${{ inputs.working_directory }}
      shell: bash

    - name: Run formatter
      if: steps.detect-ruff.outputs.ruff-available == 0
      run: poetry run ruff format --force-exclude --diff ${{ inputs.working_directory }}
      shell: bash
