name: Lint Python
description: Linting for Python projects

runs:
  using: composite
  steps:
      - name: Run linter
        uses: chartboost/ruff-action@v1

      - name: Run formatter
        uses: chartboost/ruff-action@v1
        with:
          args: format --force-exclude --check
