name: Lint Python
description: Linting for Python projects
inputs:
  exclude_trailing_comma_path:
    required: false
    description: Ignore trailing comma changes in given path
    default: ''

runs:
  using: composite
  steps:
    - run: find . -name '*.json' -type f -print0 | xargs -I {} -0 python -m json.tool --indent 2 --no-ensure-ascii {} {}
      shell: bash

    - uses: moneymeets/moneymeets-composite-actions/check-git-diff@master

    # Add trailing commas only for the excluded files, and return a zero exit code
    # even if there are changes in the files. This is done so that in the next step,
    # when add-trailing-comma is run again, the command can return a non-zero exit code
    # (and thus fail the pipeline), if any changes are made.
    - run: find ${{ inputs.exclude_trailing_comma_path }} -name '*.py' | xargs poetry run add-trailing-comma --exit-zero-even-if-changed
      if: ${{ inputs.exclude_trailing_comma_path != '' }}
      shell: bash

    # Returns non-zero exit code if any changes are made
    - run: find . -name '*.py' | xargs poetry run add-trailing-comma
      shell: bash

    - run: poetry run flake8
      shell: bash
