name: Lint Python
description: Linting for Python projects
inputs:
  exclude_trailing_comma_path:
    required: false
    description: Ignore trailing comma changes in given path
    default: ''

runs:
  using: composite
  steps:
    - run: find ${{ inputs.exclude_trailing_comma_path }} -name '*.py' | xargs poetry run add-trailing-comma --exit-zero-even-if-changed
      if: ${{ inputs.exclude_trailing_comma_path != '' }}
      shell: bash

    - run: find . -name '*.py' | xargs poetry run add-trailing-comma
      shell: bash

    - run: poetry run flake8
      shell: bash
