name: Block Poetry version downgrade
description: Block Poetry version downgrade

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: master
        ref: master

    - uses: moneymeets/moneymeets-composite-actions/detect-python-version@master
      # This is required for initial repositories
      if: ${{ hashFiles('master/poetry.lock') != '' }}
      id: detect-version-on-master
      with:
        working_directory: ${{ format('{0}/master', github.workspace) }}

    - uses: actions/checkout@v4
      with:
        path: feature-branch

    - uses: moneymeets/moneymeets-composite-actions/detect-python-version@master
      id: detect-version-on-feature-branch
      with:
        working_directory: ${{ format('{0}/feature-branch', github.workspace) }}

    - shell: bash
      # This is required for initial repositories
      if: ${{ hashFiles('master/poetry.lock') != '' && hashFiles('feature-branch/poetry.lock') != '' }}
      env:
        MASTER_POETRY_VERSION: ${{ steps.detect-version-on-master.outputs.poetry-version }}
        FEATURE_POETRY_VERSION: ${{ steps.detect-version-on-feature-branch.outputs.poetry-version }}
      run: |
        if dpkg --compare-versions "$FEATURE_POETRY_VERSION" "lt" "$MASTER_POETRY_VERSION"; then
          echo "::error file=poetry.lock,line=1::Poetry version downgrade from ${MASTER_POETRY_VERSION} to ${FEATURE_POETRY_VERSION} not allowed"
          exit 1
        else
          echo "Passed, master=$MASTER_POETRY_VERSION; feature=$FEATURE_POETRY_VERSION"
        fi

    - run: rm -r "${{ format('{0}/master', github.workspace) }}" && rm -r "${{ format('{0}/feature-branch', github.workspace) }}"
      shell: bash
